/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusAdaptor -a dbusadaptor.h:dbusadaptor.cpp harbour.slackfish.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSADAPTOR_H_1472669623
#define DBUSADAPTOR_H_1472669623

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface harbour.slackfish
 */
class DBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "harbour.slackfish")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"harbour.slackfish\">\n"
"    <method name=\"activate\"/>\n"
"  </interface>\n"
        "")
public:
    DBusAdaptor(QObject *parent);
    virtual ~DBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activate();
Q_SIGNALS: // SIGNALS
};

#endif
